name: skipapp-showcase
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '0 3,6,9,12,15,18,21 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/skip/.github/workflows/skip-app.yml@main
